INSERT INTO BOOK(PUBLISHER, COVER_STATE) VALUES('2018-10-15', 'JOHN DOE 1')
INSERT INTO BOOK(PUBLISHER, COVER_STATE) VALUES('2018-10-16', 'JOHN DOE 2')
INSERT INTO BOOK(PUBLISHER, COVER_STATE) VALUES('2018-10-17', 'JOHN DOE 3')
INSERT INTO BOOK(PUBLISHER, COVER_STATE) VALUES('2018-10-18', 'JOHN DOE 4')


INSERT INTO LABEL(TITLE, COLOR) VALUES('DUMMY TEXT 1', 'BLUE')
INSERT INTO LABEL(TITLE, COLOR) VALUES('DUMMY TEXT 2', 'BLUE')
INSERT INTO LABEL(TITLE, COLOR) VALUES('DUMMY TEXT 3', 'BLUE')
INSERT INTO LABEL(TITLE, COLOR) VALUES('DUMMY TEXT 4', 'BLUE')