CREATE TABLE BOOK (
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  PUBLISHER DATE,
  COVER_STATE TEXT
)

CREATE TABLE LABEL (
  ID GENERATED ALWAYS AS IDENTITY,
  TITLE TEXT,
  COLOR TEXT,
)